2024-12-19 19:07:32,037 INFO    MainThread:26607 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-12-19 19:07:32,038 INFO    MainThread:26607 [wandb_setup.py:_flush():76] Configure stats pid to 26607
2024-12-19 19:07:32,038 INFO    MainThread:26607 [wandb_setup.py:_flush():76] Loading settings from /Users/jaydenteoh/.config/wandb/settings
2024-12-19 19:07:32,038 INFO    MainThread:26607 [wandb_setup.py:_flush():76] Loading settings from /Users/jaydenteoh/Documents/Research/Microsoft/belief-state-transformer/wandb/settings
2024-12-19 19:07:32,038 INFO    MainThread:26607 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-12-19 19:07:32,038 INFO    MainThread:26607 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-12-19 19:07:32,038 INFO    MainThread:26607 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'bst_finetune.py', 'program_abspath': '/Users/jaydenteoh/Documents/Research/Microsoft/belief-state-transformer/bst_finetune.py', 'program': '/Users/jaydenteoh/Documents/Research/Microsoft/belief-state-transformer/bst_finetune.py'}
2024-12-19 19:07:32,038 INFO    MainThread:26607 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-12-19 19:07:32,038 INFO    MainThread:26607 [wandb_init.py:_log_setup():520] Logging user logs to /Users/jaydenteoh/Documents/Research/Microsoft/belief-state-transformer/wandb/run-20241219_190732-3zr6xau6/logs/debug.log
2024-12-19 19:07:32,038 INFO    MainThread:26607 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/jaydenteoh/Documents/Research/Microsoft/belief-state-transformer/wandb/run-20241219_190732-3zr6xau6/logs/debug-internal.log
2024-12-19 19:07:32,038 INFO    MainThread:26607 [wandb_init.py:init():560] calling init triggers
2024-12-19 19:07:32,038 INFO    MainThread:26607 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'model': 'gpt2', 'lora_r': 16, 'lora_alpha': 32, 'lora_dropout': 0.1, 'dataset': 'graph', 'n_train': 200000, 'n_test': 20000, 'num_nodes': 50, 'deg': 2, 'path_len': 5, 'mate_in': 2, 'unrolled': True, 'batch_size': 16, 'lr': 1e-05, 'weight_decay': 0.01, 'epochs': 100, 'save_every': 5000, 'teacherless': False, 'reverse': False, 'eval_train': False, 'eval_every': 5000, 'use_wandb': True, 'wandb_entity': None, 'compile': False, 'use_flash': False, 'block_size': 45, 'vocab_size': 50257, 'teacherless_token': None}
2024-12-19 19:07:32,038 INFO    MainThread:26607 [wandb_init.py:init():610] starting backend
2024-12-19 19:07:32,038 INFO    MainThread:26607 [wandb_init.py:init():614] setting up manager
2024-12-19 19:07:32,041 INFO    MainThread:26607 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-12-19 19:07:32,042 INFO    MainThread:26607 [wandb_init.py:init():622] backend started and connected
2024-12-19 19:07:32,048 INFO    MainThread:26607 [wandb_init.py:init():711] updated telemetry
2024-12-19 19:07:32,084 INFO    MainThread:26607 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-12-19 19:07:32,835 INFO    MainThread:26607 [wandb_run.py:_on_init():2396] communicating current version
2024-12-19 19:07:32,904 INFO    MainThread:26607 [wandb_run.py:_on_init():2405] got version response upgrade_message: "wandb version 0.19.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-12-19 19:07:32,904 INFO    MainThread:26607 [wandb_init.py:init():795] starting run threads in backend
2024-12-19 19:07:36,712 WARNING MainThread:26607 [wandb_init.py:init():1168] interrupted
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
           ^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 808, in init
    run_start_result = run_start_handle.wait(timeout=30)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-12-19 19:07:42,703 WARNING MsgRouterThr:26607 [router.py:message_loop():77] message_loop has been closed
